# Generated by Django 3.2.12 on 2022-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20220415_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tax_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'New'), (2, 'Paid'), (3, 'Delayed')], null=True),
        ),
    ]
